version: '1.0'
stages:
  - "clone"
  - "build"
  - "deploy"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "guysalton-codefresh/greeting"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
    git: guyGithub
  BuildingDockerImage:
    stage: "build"
    title: Building Docker Image
    type: build
    image_name: trivial-web
    working_directory: ./example/
    tag: '${{CF_SHORT_REVISION}}'
    dockerfile: Dockerfile
  canaryDeploy:
    stage: "deploy"
    title: "Deploying new version ${{CF_SHORT_REVISION}}"
    image: codefresh/k8s-canary:master
    environment:
      - WORKING_VOLUME=.
      - SERVICE_NAME=my-demo-app
      - DEPLOYMENT_NAME=my-demo-app
      - TRAFFIC_INCREMENT=20
      - NEW_VERSION=${{CF_SHORT_REVISION}}
      - SLEEP_SECONDS=40
      - NAMESPACE=canary
      - KUBE_CONTEXT=aks
  
